### ISSUE TITLE
PIFuの環境構築

### ISSUE THREAD

**Issue by nktuk** [jo-315/ai_lesson#1]
[やりたいこと]
①https://github.com/shunsukesaito/PIFu
 ↑を、使えるようにする。

[現状]
②https://www.jyuko49.com/entry/2020/03/07/184549
 ①はWindows用なので、Mac用の②を参考に環境構築中。

エラーはこれ。
`matsudayuri@localhost: $ git clone https://github.com/shunsukesaito/PIFu.git                        [/Users/matsudayuri/Downloads/playground/ai_lesson/model]
Cloning into 'PIFu'...
remote: Enumerating objects: 200, done.
remote: Total 200 (delta 0), reused 0 (delta 0), pack-reused 200
Receiving objects: 100% (200/200), 2.42 MiB | 2.20 MiB/s, done.
Resolving deltas: 100% (82/82), done.
matsudayuri@localhost: $ cd PIFu                                                                    [/Users/matsudayuri/Downloads/playground/ai_lesson/model]
matsudayuri@localhost: $ sh ./scripts/download_trained_model.sh                                [/Users/matsudayuri/Downloads/playground/ai_lesson/model/PIFu]
+ mkdir -p checkpoints
+ cd checkpoints
+ wget 'https://drive.google.com/uc?export=download&id=1zEmVXG2VHy0MMzngcRshB4D8Sr_oLHsm' -O net_G
--2021-01-14 21:18:50--  https://drive.google.com/uc?export=download&id=1zEmVXG2VHy0MMzngcRshB4D8Sr_oLHsm
Resolving drive.google.com (drive.google.com)... 216.58.196.238
Connecting to drive.google.com (drive.google.com)|216.58.196.238|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-14-0o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0rl366msttg1mohn0341j4c64vq42p4b/1610626725000/14428417455748421393/*/1zEmVXG2VHy0MMzngcRshB4D8Sr_oLHsm?e=download [following]
Warning: wildcards not supported in HTTP.
--2021-01-14 21:18:52--  https://doc-14-0o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0rl366msttg1mohn0341j4c64vq42p4b/1610626725000/14428417455748421393/*/1zEmVXG2VHy0MMzngcRshB4D8Sr_oLHsm?e=download
Resolving doc-14-0o-docs.googleusercontent.com (doc-14-0o-docs.googleusercontent.com)... 172.217.26.97
Connecting to doc-14-0o-docs.googleusercontent.com (doc-14-0o-docs.googleusercontent.com)|172.217.26.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘net_G’

net_G                                       [           <=>                                                                ]  59.61M  27.7MB/s    in 2.2s    

2021-01-14 21:18:55 (27.7 MB/s) - ‘net_G’ saved [62510909]

+ wget 'https://drive.google.com/uc?export=download&id=1V83B6GDIjYMfHdpg-KcCSAPgHxpafHgd' -O net_C
--2021-01-14 21:18:55--  https://drive.google.com/uc?export=download&id=1V83B6GDIjYMfHdpg-KcCSAPgHxpafHgd
Resolving drive.google.com (drive.google.com)... 216.58.196.238
Connecting to drive.google.com (drive.google.com)|216.58.196.238|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-00-0o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/beta5qrq29vv2h6qqg6ds6aapm6ql4b2/1610626725000/14428417455748421393/*/1V83B6GDIjYMfHdpg-KcCSAPgHxpafHgd?e=download [following]
Warning: wildcards not supported in HTTP.
--2021-01-14 21:18:57--  https://doc-00-0o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/beta5qrq29vv2h6qqg6ds6aapm6ql4b2/1610626725000/14428417455748421393/*/1V83B6GDIjYMfHdpg-KcCSAPgHxpafHgd?e=download
Resolving doc-00-0o-docs.googleusercontent.com (doc-00-0o-docs.googleusercontent.com)... 172.217.26.97
Connecting to doc-00-0o-docs.googleusercontent.com (doc-00-0o-docs.googleusercontent.com)|172.217.26.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘net_C’

net_C                                       [      <=>                                                                     ]  34.88M  29.6MB/s    in 1.2s    

2021-01-14 21:18:59 (29.6 MB/s) - ‘net_C’ saved [36570643]

+ cd ..
matsudayuri@localhost: $ pip install -r requirements.txt                                       [/Users/matsudayuri/Downloads/playground/ai_lesson/model/PIFu]
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32
ERROR: No matching distribution found for opencv-python==4.2.0.32
`

[やったこと]
・opencv-pythonver4.2.0.32の有無確認、あり。`pip install opencv-python==4.2.0.32`とするが、ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32
ERROR: No matching distribution found for opencv-python==4.2.0.32
・requirements.txt内で、エラー表示のでたライブラリ？のver指定をなくす。→ pip install -r requirements.txtですごいデカいエラーでて力尽き...ました....

[明日やる]
・pythonをverを下げる。

**Comment by jo-315** [comment]
https://pypi.org/project/opencv-python/4.2.0.32/ のFAQで以下がありました。
![スクリーンショット 2021-01-15 0 39 05](https://user-images.githubusercontent.com/32921100/104613082-36573700-56ca-11eb-885f-a20412de572d.png)

あまりちゃんと理解してないですが、pipでpythonの2系が使われてないですか？？`pip3 install hogehoge`でやってみるとか？？

あと蛇足ですが、requirement.txtは更新が止まっているみたいなので、適宜変えてもいいかもですね

**Comment by nktuk** [comment]
すごい...優秀...ありがとおおおおお

pip3は大丈夫そう...
requirements.txtを最新版にしてみます！
shapelyがうまくインストールできてみたいなので調査中ですー。

**Comment by nktuk** [comment]
解決しました！
shapelyのインストールにGeosが必要でした。
`brew install geos`で解決。
