### ISSUE TITLE
test.shの実行

### ISSUE THREAD

**Issue by nktuk** [jo-315/ai_lesson#2]
[やりたいこと]
` sh ./scripts/test.sh` の実行。

[現状]
下記エラーが発生した。
```
+ GPU_ID=0
+ DISPLAY_ID=10
+ NAME=pifu_demo
+ BATCH_SIZE=1
+ MLP_DIM='257 1024 512 256 128 1'
+ MLP_DIM_COLOR='513 1024 512 256 128 3'
+ VOL_RES=256
+ CHECKPOINTS_NETG_PATH=./checkpoints/net_G
+ CHECKPOINTS_NETC_PATH=./checkpoints/net_C
+ TEST_FOLDER_PATH=./sample_images
+ CUDA_VISIBLE_DEVICES=0
+ python ./apps/eval.py --name pifu_demo --batch_size 1 --mlp_dim 257 1024 512 256 128 1 --mlp_dim_color 513 1024 512 256 128 3 --num_stack 4 --num_hourglass 2 --resolution 256 --hg_down ave_pool --norm group --norm_color group --test_folder_path ./sample_images --load_netG_checkpoint_path ./checkpoints/net_G --load_netC_checkpoint_path ./checkpoints/net_C
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './apps/eval.py': [Errno 2] No such file or directory

````
python2.7で実行されているが、当環境では、3.9.1であることが問題？
※ `python -V`  だとPython 2.7.16
※ `python3 -V` だとpython3.9.1

もしかして、2.7.16だったとしても問題ですかね？

[試みたこと]
・./checkpoints/net_Cもしくはnet_G内にpython2.7の表記があれば3.9.1に変更する。
> このファイルはバイナリか、サポートされていないテキストエンコードお使用しているため、エディターに表示されません。このまま開きますか？

Vscodeで開けず。

・バイナリデータもしくはサポートされていないファイルの変更方法
vimであればコンパイル前のファイルで開けるとのこと。
が、よくわからない中身が現れたので力尽きました。

[明日やる]
・このファイルは〜の編集の仕方をやってみる。

**Comment by jo-315** [comment]
すでに検討済みなら申し訳ないですが、純粋に`apps/eval.py`（cloneしたレポジトリ内のファイル）へのpathがズレているのでは？？あと、pythonの3系使うなら、shellscript書き換えた方が早いと思います。

**Comment by nktuk** [comment]
検討済みじゃなかったので助かってます・・！！
test.sh内のpathを変更してみたところ、エラーが変わったので調査中です。

それと

> shellscriptを書き換える

が、よく分からなくて...↓このようなことを指してますか？
http://auewe.hatenablog.com/entry/2013/10/16/095026

**Comment by jo-315** [comment]
test.shの25行を
```
CUDA_VISIBLE_DEVICES=${GPU_ID} python ./apps/eval.py \
```
から
```
CUDA_VISIBLE_DEVICES=${GPU_ID} python3 ./apps/eval.py \
```
にしてみる。多分変わるはず！

**Comment by nktuk** [comment]
ありがとう！
指摘の通りにして、
test.sh内の別のパスを訂正したら実行できました！

```CHECKPOINTS_NETG_PATH='../checkpoints/net_G'
CHECKPOINTS_NETC_PATH='../checkpoints/net_C'

TEST_FOLDER_PATH='../sample_images'
```
